class ExpectedLineup():
    match_date
    leauge
    home_team
    away_team
    home_player1
    home_player2
    home_player3
    home_player4
    home_player5
    home_player6
    home_player7
    home_player8
    home_player9
    home_player10
    home_player11
    away_player1
    away_player2
    away_player3
    away_player4
    away_player5
    away_player6
    away_player7
    away_player8
    away_player9
    away_player10
    away_player11