# Define here the models for your scraped Fields
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/Fields.html

import scrapy

class Player(scrapy.Item):

    update_date = scrapy.Field()
    age = scrapy.Field()
    birthday = scrapy.Field()
    height = scrapy.Field()
    nationality = scrapy.Field()
    all_positions = scrapy.Field()
    player_name = scrapy.Field()
    player_full_name = scrapy.Field()
    weight = scrapy.Field()
    overall_rating= scrapy.Field()
    potential= scrapy.Field()
    value = scrapy.Field()
    wage = scrapy.Field()

    #Profile
    preferred_foot= scrapy.Field()
    skill_moves = scrapy.Field()
    weak_foot = scrapy.Field()
    reputation = scrapy.Field()
    attacking_work_rate= scrapy.Field()
    defensive_work_rate = scrapy.Field()
    body_type = scrapy.Field()
    real_face = scrapy.Field()
    sofifa_id= scrapy.Field()

    #specialities
    specialities = scrapy.Field()

    #Team information
    team1 = scrapy.Field()
    team1_rating = scrapy.Field()
    team1_position = scrapy.Field()
    team1_kitnum = scrapy.Field()
    team1_loaned_from = scrapy.Field()
    team1_joined = scrapy.Field()
    team1_contract = scrapy.Field()
    team2= scrapy.Field()
    team2_rating = scrapy.Field()
    team2_position = scrapy.Field()
    team2_kitnum = scrapy.Field()

    acceleration = scrapy.Field()
    aggression = scrapy.Field()
    agility = scrapy.Field()
    balance = scrapy.Field()
    ball_control = scrapy.Field()
    composure = scrapy.Field()
    crossing = scrapy.Field()
    curve = scrapy.Field()
    marking = scrapy.Field()
    defensive_awareness = scrapy.Field()
    dribbling = scrapy.Field()
    finishing = scrapy.Field()
    fk_accuracy= scrapy.Field()
    gk_diving= scrapy.Field()
    gk_handling= scrapy.Field()
    gk_kicking= scrapy.Field()
    gk_positioning= scrapy.Field()
    gk_reflexes= scrapy.Field()
    heading_accuracy= scrapy.Field()
    interceptions= scrapy.Field()
    jumping= scrapy.Field()
    long_passing= scrapy.Field()
    long_shots= scrapy.Field()
    penalties= scrapy.Field()
    positioning= scrapy.Field()
    reactions= scrapy.Field()
    short_passing= scrapy.Field()
    shot_power= scrapy.Field()
    sliding_tackle= scrapy.Field()
    sprint_speed= scrapy.Field()
    stamina= scrapy.Field()
    standing_tackle= scrapy.Field()
    strength= scrapy.Field()
    update_date= scrapy.Field()
    vision= scrapy.Field()
    volleys= scrapy.Field()
    
    traits = scrapy.Field()

class PlayerInfo(scrapy.Item):
    birthday = scrapy.Field()
    height = scrapy.Field()
    nationality = scrapy.Field()
    player_fifaId = scrapy.Field()
    player_name = scrapy.Field()
    player_full_name = scrapy.Field()
    weight = scrapy.Field()
    team = scrapy.Field()

class PlayerStats(scrapy.Item):
    acceleration = scrapy.Field()
    aggression = scrapy.Field()
    agility = scrapy.Field()
    attacking_work_rate= scrapy.Field()
    balance = scrapy.Field()
    ball_control = scrapy.Field()
    composure = scrapy.Field()
    crossing = scrapy.Field()
    curve = scrapy.Field()
    defensive_awareness = scrapy.Field()
    defensive_work_rate = scrapy.Field()
    dribbling = scrapy.Field()
    finishing = scrapy.Field()
    fk_accuracy= scrapy.Field()
    gk_diving= scrapy.Field()
    gk_handling= scrapy.Field()
    gk_kicking= scrapy.Field()
    gk_positioning= scrapy.Field()
    gk_reflexes= scrapy.Field()
    heading_accuracy= scrapy.Field()
    interceptions= scrapy.Field()
    jumping= scrapy.Field()
    long_passing= scrapy.Field()
    long_shots= scrapy.Field()
    overall_rating= scrapy.Field()
    penalties= scrapy.Field()
    player_fifaId= scrapy.Field()
    positioning= scrapy.Field()
    potential= scrapy.Field()
    preferred_foot= scrapy.Field()
    reactions= scrapy.Field()
    short_passing= scrapy.Field()
    shot_power= scrapy.Field()
    sliding_tackle= scrapy.Field()
    sprint_speed= scrapy.Field()
    stamina= scrapy.Field()
    standing_tackle= scrapy.Field()
    strength= scrapy.Field()
    update_date= scrapy.Field()
    vision= scrapy.Field()
    volleys= scrapy.Field()
    position = scrapy.Field()
    weak_foot = scrapy.Field()

class TeamStats(scrapy.Item):
    team_id = scrapy.Field()
    team_name = scrapy.Field()
    leauge = scrapy.Field()
    update_date= scrapy.Field()

    overall = scrapy.Field()
    attack = scrapy.Field()
    midfield = scrapy.Field()
    defence = scrapy.Field()

    defensive_style = scrapy.Field()
    defence_width = scrapy.Field()
    defence_depth = scrapy.Field()
    build_up_play = scrapy.Field() 
    chance_creation = scrapy.Field()
    offense_width = scrapy.Field()
    players_in_box = scrapy.Field()
    corners = scrapy.Field()
    free_kicks = scrapy.Field()

class TeamSquad(scrapy.Item):
    player_shortName = scrapy.Field()
    player_fullName = scrapy.Field()
    player_transfermarktId = scrapy.Field()
    birthday = scrapy.Field()
    team = scrapy.Field()
    position = scrapy.Field()
    season = scrapy.Field()
    status = scrapy.Field()
class fbref_MatchSquad(scrapy.Item):
    fbrefMatchId = scrapy.Field()
    player_name = scrapy.Field()
    player_kitnum = scrapy.Field()
    team = scrapy.Field()
    is_home_team = scrapy.Field()
    is_sub = scrapy.Field()

class fbref_MatchGoals(scrapy.Item):
    fbrefMatchId = scrapy.Field()
    player_name = scrapy.Field()
    minute = scrapy.Field()
    type_of_goal = scrapy.Field()
    team = scrapy.Field()
    is_home_team = scrapy.Field()

class fbref_MatchStats(scrapy.Item):
    fbrefMatchId = scrapy.Field()
    team = scrapy.Field()
    is_home_team = scrapy.Field()
    score = scrapy.Field()
    manager = scrapy.Field()
    captain = scrapy.Field()
    
    formation = scrapy.Field()
    possession = scrapy.Field()

    fouls = scrapy.Field()
    corners= scrapy.Field()
    crosses= scrapy.Field()
    touches = scrapy.Field()
    tackles = scrapy.Field()
    interceptions= scrapy.Field()
    aerials_won= scrapy.Field()
    clearances= scrapy.Field()
    offsides = scrapy.Field()
    goal_kicks = scrapy.Field()
    throw_ins = scrapy.Field()
    long_balls = scrapy.Field()

    total_players_stats = scrapy.Field()

    minutes = scrapy.Field()
    Gls	= scrapy.Field()
    Ast= scrapy.Field()
    PK= scrapy.Field()
    PKatt= scrapy.Field()
    Sh= scrapy.Field()
    SoT= scrapy.Field()
    CrdY= scrapy.Field()
    CrdR= scrapy.Field()
    Touches= scrapy.Field()
    Tkl= scrapy.Field()
    Int= scrapy.Field()
    Blocks = scrapy.Field()

    xG= scrapy.Field()
    npxG= scrapy.Field()
    xAG= scrapy.Field()

    SCA= scrapy.Field()
    GCA= scrapy.Field()
    Passes_Cmp = scrapy.Field()
    Passes_Att= scrapy.Field()
    Passes_CmpPercentage = scrapy.Field()
    Passes_PrgP = scrapy.Field()

    Carries = scrapy.Field()
    Carries_PrgC = scrapy.Field()

    Take_Ons_Att = scrapy.Field()
    Take_Ons_Succ = scrapy.Field()


class fbref_MatchPlayerStats(scrapy.Item):
    fbrefMatchId = scrapy.Field()
    player_name = scrapy.Field()
    player_kitnum = scrapy.Field()
    team = scrapy.Field()
    nationality = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    minutes = scrapy.Field()
    Gls	= scrapy.Field()
    Ast= scrapy.Field()
    PK= scrapy.Field()
    PKatt= scrapy.Field()
    Sh= scrapy.Field()
    SoT= scrapy.Field()
    CrdY= scrapy.Field()
    CrdR= scrapy.Field()
    Touches= scrapy.Field()
    Tkl= scrapy.Field()
    Int= scrapy.Field()
    Blocks = scrapy.Field()

    xG= scrapy.Field()
    npxG= scrapy.Field()
    xAG= scrapy.Field()

    SCA= scrapy.Field()
    GCA= scrapy.Field()
    Passes_Cmp = scrapy.Field()
    Passes_Att= scrapy.Field()
    Passes_CmpPercentage = scrapy.Field()
    Passes_PrgP = scrapy.Field()

    Carries = scrapy.Field()
    Carries_PrgC = scrapy.Field()

    Take_Ons_Att = scrapy.Field()
    Take_Ons_Succ = scrapy.Field()
class fbref_MatchInfos(scrapy.Item):
    fbrefMatchId = scrapy.Field()
    fbrefURL = scrapy.Field()
    leauge = scrapy.Field()
    season = scrapy.Field()
    match_date = scrapy.Field()
    match_date_str = scrapy.Field()
    match_week = scrapy.Field()
    venue_time = scrapy.Field()
    # local_time = scrapy.Field() Ko lay duoc
    attendance = scrapy.Field()
    venue = scrapy.Field()
    officials = scrapy.Field()
    home_team = scrapy.Field()
    away_team = scrapy.Field()