# Generated by Django 5.0 on 2023-12-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_matchsdatasetmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Scores_And_Fixtures',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('league', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('match_week', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('match_date', models.DateField()),
                ('venue_time', models.CharField(max_length=255)),
                ('attendance', models.IntegerField()),
                ('stadium', models.CharField(max_length=255)),
                ('officials', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
            ],
            options={
                'db_table': 'view_scores_and_fixtures',
                'managed': False,
            },
        ),
    ]
