# Generated by Django 5.0 on 2023-12-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_matchs_dataset_model_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fbref_Matchgoals_Modified',
        ),
        migrations.DeleteModel(
            name='Fbref_Matchinfos_Modified',
        ),
        migrations.DeleteModel(
            name='Fbref_Matchplayerstats_Modified',
        ),
        migrations.DeleteModel(
            name='Fbref_Matchsquad_Modified',
        ),
        migrations.DeleteModel(
            name='Fbref_Matchstats_Modified',
        ),
        migrations.DeleteModel(
            name='Matchsquad_Players',
        ),
        migrations.DeleteModel(
            name='Sofifa_Players_Attr_Modified',
        ),
        migrations.DeleteModel(
            name='Sofifa_Players_Infos_Modified',
        ),
        migrations.DeleteModel(
            name='Matchs_Dataset_Model',
        ),
    ]
