# Generated by Django 5.0 on 2023-12-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchsdatasetmodel',
            table='matchs_dataset_modell',
        ),
    ]
