# Generated by Django 5.0 on 2023-12-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_matchsdatasetmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchsdatasetmodel',
            table='matchs_dataset_model',
        ),
    ]
