# Generated by Django 5.0 on 2023-12-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_futurematches'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofifa_id', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Sofifa_Id', max_length=100, null=True)),
                ('team1', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Team1', max_length=100, null=True)),
                ('team2', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Team2', max_length=100, null=True)),
                ('player_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Player_Name', max_length=100, null=True)),
                ('all_positions', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='All_Positions', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('overall_rating', models.FloatField(blank=True, db_column='Overall_Rating', null=True)),
                ('potential', models.FloatField(blank=True, db_column='Potential', null=True)),
                ('value', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Value', max_length=100, null=True)),
                ('team1_position', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Team1_Position', max_length=100, null=True)),
            ],
            options={
                'db_table': 'sofifa_players_attr_modified',
                'managed': False,
            },
        ),
    ]
