# Generated by Django 5.0 on 2023-12-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_teamoptimization'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teamoptimization',
            table='team_optimization',
        ),
    ]
